version: "3.9"

services:
  postgres:
    image: postgres:17

    container_name: clinexa-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: clinexa
      POSTGRES_PASSWORD: clinexa123
      POSTGRES_DB: clinexa

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: