export const PermissionCodes = {
  // Administration

  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_READ: 'PERMISSION_READ',

  // Patient

  PATIENT_READ: 'PATIENT_READ',
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_UPDATE: 'PATIENT_UPDATE',
  PATIENT_DELETE: 'PATIENT_DELETE',

  // Doctor

  DOCTOR_READ: 'DOCTOR_READ',
  DOCTOR_CREATE: 'DOCTOR_CREATE',
  DOCTOR_UPDATE: 'DOCTOR_UPDATE',
  DOCTOR_DELETE: 'DOCTOR_DELETE',

  // Appointment

  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',

  // Medical Record

  MEDICAL_RECORD_READ: 'MEDICAL_RECORD_READ',
  MEDICAL_RECORD_CREATE: 'MEDICAL_RECORD_CREATE',
  MEDICAL_RECORD_UPDATE: 'MEDICAL_RECORD_UPDATE',
  MEDICAL_RECORD_DELETE: 'MEDICAL_RECORD_DELETE',

  // Laboratory

  LAB_READ: 'LAB_READ',
  LAB_CREATE: 'LAB_CREATE',
  LAB_UPDATE: 'LAB_UPDATE',
  LAB_DELETE: 'LAB_DELETE',

  // Pharmacy

  PHARMACY_READ: 'PHARMACY_READ',
  PHARMACY_CREATE: 'PHARMACY_CREATE',
  PHARMACY_UPDATE: 'PHARMACY_UPDATE',
  PHARMACY_DELETE: 'PHARMACY_DELETE',

  // Billing

  BILLING_READ: 'BILLING_READ',
  BILLING_CREATE: 'BILLING_CREATE',
  BILLING_UPDATE: 'BILLING_UPDATE',
  BILLING_REFUND: 'BILLING_REFUND',

  // Inventory

  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_CREATE: 'INVENTORY_CREATE',
  INVENTORY_UPDATE: 'INVENTORY_UPDATE',
  INVENTORY_DELETE: 'INVENTORY_DELETE',

  // Reports

  REPORT_READ: 'REPORT_READ',
  REPORT_EXPORT: 'REPORT_EXPORT',

  // Settings

  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  DEPARTMENT_READ: 'DEPARTMENT_READ',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',

  CLINIC_CREATE: 'CLINIC_CREATE',
  CLINIC_READ: 'CLINIC_READ',
  CLINIC_UPDATE: 'CLINIC_UPDATE',
  CLINIC_DELETE: 'CLINIC_DELETE',

  PRESCRIPTION_READ: 'PRESCRIPTION_READ',
  PRESCRIPTION_CREATE: 'PRESCRIPTION_CREATE',
  PRESCRIPTION_UPDATE: 'PRESCRIPTION_UPDATE',
  PRESCRIPTION_DELETE: 'PRESCRIPTION_DELETE',

  DIAGNOSIS_READ: 'DIAGNOSIS_READ',
  DIAGNOSIS_CREATE: 'DIAGNOSIS_CREATE',
  DIAGNOSIS_UPDATE: 'DIAGNOSIS_UPDATE',
  DIAGNOSIS_DELETE: 'DIAGNOSIS_DELETE',
} as const;

export type PermissionCode =
  (typeof PermissionCodes)[keyof typeof PermissionCodes];
